endpoints:
    - path: "/graphql"
      method: post
      graphql:
        schema:
          {
          "__schema": {
            "queryType": { "name": "Query" },
            "subscriptionType": null,
            "types": [
              {
                "kind": "OBJECT",
                "name": "Query",
                "description": "",
                "fields": [
                  {
                    "name": "allActiveClips",
                    "description": "Get all auctions",
                    "args": [],
                    "type": {
                      "kind": "LIST",
                      "name": null,
                      "ofType": { "kind": "Object", "name": "Clip", "ofType": null }
                    },
                    "isDeprecated": false,
                    "deprecationReason": null
                  }
                ],
                "inputFields": null,
                "interfaces": [],
                "enumValues": null,
                "possibleTypes": null
              },
              {
                "kind": "OBJECT",
                "name": "Clip",
                "description": "",
                "fields": [
                  {
                    "name": "saleId",
                    "description": "",
                    "args": [],
                    "type": {
                      "kind": "SCALAR",
                      "name": "Int",
                      "ofType": null
                    },
                    "isDeprecated": false,
                    "deprecationReason": null
                  },
                  {
                    "name": "urn",
                    "description": "",
                    "args": [],
                    "type": {
                      "kind": "SCALAR",
                      "name": "String",
                      "ofType": null
                    },
                    "isDeprecated": false,
                    "deprecationReason": null
                  },
                  {
                    "name": "tab",
                    "description": "",
                    "args": [],
                    "type": {
                      "kind": "SCALAR",
                      "name": "Float",
                      "ofType": null
                    },
                    "isDeprecated": false,
                    "deprecationReason": null
                  },
                  {
                    "name": "lot",
                    "description": "",
                    "args": [],
                    "type": {
                      "kind": "SCALAR",
                      "name": "Float",
                      "ofType": null
                    },
                    "isDeprecated": false,
                    "deprecationReason": null
                  },
                  {
                    "name": "tic",
                    "description": "",
                    "args": [],
                    "type": {
                      "kind": "SCALAR",
                      "name": "Int",
                      "ofType": null
                    },
                    "isDeprecated": false,
                    "deprecationReason": null
                  },
                  {
                    "name": "top",
                    "description": "",
                    "args": [],
                    "type": {
                      "kind": "SCALAR",
                      "name": "Float",
                      "ofType": null
                    },
                    "isDeprecated": false,
                    "deprecationReason": null
                  }
                ],
                "inputFields": null,
                "interfaces": [],
                "enumValues": null,
                "possibleTypes": null
              },
              {
                "kind": "SCALAR",
                "name": "String",
                "description": "The `String` scalar type represents textual data, represented as UTF-8 character sequences. The String type is most often used by GraphQL to represent free-form human-readable text.",
                "fields": null,
                "inputFields": null,
                "interfaces": null,
                "enumValues": null,
                "possibleTypes": null
              },
              {
                "kind": "SCALAR",
                "name": "Int",
                "description": "The `Int` scalar type represents non-fractional signed whole numeric values. Int can represent values between -(2^31) and 2^31 - 1.",
                "fields": null,
                "inputFields": null,
                "interfaces": null,
                "enumValues": null,
                "possibleTypes": null
              },
              {
                "kind": "SCALAR",
                "name": "Float",
                "description": "The `Float` scalar type represents signed double-precision fractional values as specified by [IEEE 754](https://en.wikipedia.org/wiki/IEEE_floating_point).",
                "fields": null,
                "inputFields": null,
                "interfaces": null,
                "enumValues": null,
                "possibleTypes": null
              },
            ],
            "directives": []
          }
        }
